# ETL Framework Test Configuration
# This file is used for testing the ETL framework configuration validation

global:
  timezone: "UTC"
  log_level: "INFO"
  default_retries: 3
  default_retry_delay: 5

env:
  DATABASE_URL: "postgresql://user:password@localhost:5432/mydatabase"
  API_KEY: "your_api_key"
  DATA_PATH: "/mnt/data"

pipelines:
  - name: "example_pipeline"
    description: "An example pipeline for testing ETL framework"
    version: "1.0.0"
    timeout_seconds: 3600
    tags:
      - example
      - test
    schedule:
      cron: "0 2 * * *"
      timezone: "UTC"
      enabled: true
    checkpointing:
      enabled: true
      location: "s3://checkpoints/example_pipeline/"
      strategy: "incremental"
    extractor:
      type: "PostgresExtractor"
      compute_strategy:
        mode: "local"
        workers: 1
      config:
        query: "SELECT * FROM users WHERE updated_at >= :last_run"
        connection_id: "postgres_main"
    transformers:
      - type: "CleanUserData"
        compute_strategy:
          mode: "thread"
          workers: 4
        config:
          remove_duplicates: true
      - type: "NormalizeFields"
        compute_strategy:
          mode: "local"
          workers: 1
        config:
          fields:
            - name
            - email
    loader:
      type: "S3Loader"
      compute_strategy:
        mode: "process"
        workers: 2
      config:
        bucket: "analytics-data"
        prefix: "users/"
